apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxwizard-deployment
  namespace: etsi-taxwizard-app
  labels:
    app: taxwizard-appcl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: taxwizard-app
  template:
    metadata:
      labels:
        app: taxwizard-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: taxwizard
        image: eessah/twetsiwebapi:ernestlatest1.1
        ports:
        - name: https
          containerPort: 80
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux