apiVersion: v1
kind: Service
metadata:
  name: taxwizard-app-service 
  labels:
    app: taxwizard-app
spec:
  type: LoadBalancer
  selector:    
    app: taxwizard-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80